Interest.create("id"=>2, "interest_name"=>"video games", "interest_count"=>0)
Interest.create("id"=>3, "interest_name"=>"music", "interest_count"=>0)
Interest.create("id"=>4, "interest_name"=>"movies", "interest_count"=>0)
Interest.create("id"=>5, "interest_name"=>"exercise", "interest_count"=>0)
Interest.create("id"=>6, "interest_name"=>"books", "interest_count"=>0)
Interest.create("id"=>7, "interest_name"=>"outdoors", "interest_count"=>0)
Interest.create("id"=>8, "interest_name"=>"3D printing", "interest_count"=>0)
Interest.create("id"=>9, "interest_name"=>"photography", "interest_count"=>0)
Interest.create("id"=>10, "interest_name"=>"sports", "interest_count"=>0)
Interest.create("id"=>11, "interest_name"=>"math", "interest_count"=>0)
Interest.create("id"=>12, "interest_name"=>"technology", "interest_count"=>0)
Interest.create("id"=>13, "interest_name"=>"anime", "interest_count"=>0)
Interest.create("id"=>14, "interest_name"=>"cooking", "interest_count"=>0)
Interest.create("id"=>15, "interest_name"=>"dancing", "interest_count"=>0)
Interest.create("id"=>16, "interest_name"=>"cars", "interest_count"=>0)
Interest.create("id"=>17, "interest_name"=>"video and film", "interest_count"=>0)
Interest.create("id"=>18, "interest_name"=>"tabletop games", "interest_count"=>0)
Interest.create("id"=>19, "interest_name"=>"gardening", "interest_count"=>0)
Interest.create("id"=>20, "interest_name"=>"firearms", "interest_count"=>0)
Interest.create("id"=>21, "interest_name"=>"makeup", "interest_count"=>0)
User.create("id"=>1, "email"=>"sachavan@mail.csuchico.edu", "username"=>"Subhed", "role"=>1, "interest"=>nil, "major"=>nil, "dob"=>nil, "gender"=>nil, "password_digest"=>"efb27c97b6e91a19a63ff3cc6c0d7d63", "uid"=>"111968991048320647765", "provider"=>"google_oauth2")
User.create("id"=>2, "email"=>"kbuffardi@csuchico.edu", "username"=>"Kevin", "role"=>1, "interest"=>nil, "major"=>nil, "dob"=>nil, "gender"=>nil, "password_digest"=>"4b3599a26f57ef6270e1eede7c9ee33a", "uid"=>"113013612893127331342", "provider"=>"google_oauth2")
Concept.create("id"=>2, "name"=>"functions")
Concept.create("id"=>3, "name"=>"function parameter")
Concept.create("id"=>4, "name"=>"decision")
Concept.create("id"=>5, "name"=>"loop")
Concept.create("id"=>6, "name"=>"operation")
Concept.create("id"=>7, "name"=>"variable")
Concept.create("id"=>8, "name"=>"boolean expression")
Concept.create("id"=>9, "name"=>"array")
Concept.create("id"=>11, "name"=>"vector")
Concept.create("id"=>12, "name"=>"matrix")
Concept.create("id"=>13, "name"=>"number system")
Concept.create("id"=>14, "name"=>"recursion")
Concept.create("id"=>15, "name"=>"struct")
Concept.create("id"=>16, "name"=>"pointer")
Concept.create("id"=>17, "name"=>"sorting")
Concept.create("id"=>18, "name"=>"input/output")
Concept.create("id"=>19, "name"=>"class")
Concept.create("id"=>20, "name"=>"randomization")
Concept.create("id"=>21, "name"=>"file stream")
Video.create("video_id"=>1, "user"=>2, "vtitle"=>"Showing a workout routine with C++ vectors and for loops","concepts"=>5,"interests"=>10,"cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1469/practice")
