#User seeds
User.create("id"=>1, "email"=>"kbuffardi@csuchico.edu", "username"=>"Kevin", "role"=>1, "interest"=>nil, "major"=>nil, "dob"=>nil, "gender"=>nil, "password_digest"=>"4b3599a26f57ef6270e1eede7c9ee33a", "uid"=>"113013612893127331342", "provider"=>"google_oauth2")

#Interest seeds
Interest.create("id"=>1, "interest_name"=>"STEM", "interest_count"=>0)
Interest.create("id"=>2, "interest_name"=>"Games", "interest_count"=>0)
Interest.create("id"=>3, "interest_name"=>"Interdisciplinary", "interest_count"=>0)
Interest.create("id"=>4, "interest_name"=>"Automotive", "interest_count"=>0)
Interest.create("id"=>5, "interest_name"=>"Fashion & Cosmetics", "interest_count"=>0)
Interest.create("id"=>6, "interest_name"=>"Arts & Crafts", "interest_count"=>0)
Interest.create("id"=>7, "interest_name"=>"Reading", "interest_count"=>0)
Interest.create("id"=>8, "interest_name"=>"Multimedia", "interest_count"=>0)
Interest.create("id"=>9, "interest_name"=>"Relaxation", "interest_count"=>0)
Interest.create("id"=>10, "interest_name"=>"Socializing", "interest_count"=>0)
Interest.create("id"=>11, "interest_name"=>"Athletics", "interest_count"=>0)
Interest.create("id"=>12, "interest_name"=>"Nature", "interest_count"=>0)
Interest.create("id"=>13, "interest_name"=>"Culinary", "interest_count"=>0)
Interest.create("id"=>14, "interest_name"=>"Travel", "interest_count"=>0)
Interest.create("id"=>15, "interest_name"=>"Animals", "interest_count"=>0)
Interest.create("id"=>16, "interest_name"=>"Adulting", "interest_count"=>0)

#Concept seeds
Concept.create("id"=>1, "name"=>"Variables")
Concept.create("id"=>2, "name"=>"Conditions")
Concept.create("id"=>3, "name"=>"While loops")
Concept.create("id"=>4, "name"=>"For loops")
Concept.create("id"=>5, "name"=>"Switch statements")
Concept.create("id"=>6, "name"=>"Vectors")
Concept.create("id"=>7, "name"=>"Functions")
Concept.create("id"=>8, "name"=>"Function parameters")
Concept.create("id"=>9, "name"=>"Arrays")
Concept.create("id"=>10, "name"=>"Pointers")
Concept.create("id"=>11, "name"=>"Structs")
Concept.create("id"=>12, "name"=>"Classes")

#Video seeds
Video.create("user"=>1, "video_id"=>"BVK6rCz_7SQ", "vtitle"=>"Variables in C++ for Soccer Players", "concepts"=>1, "interests"=>11, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/955/practice")
Video.create("user"=>1, "video_id"=>"APtxCYdcNcQ", "vtitle"=>"Variables in C++ for Constellations", "concepts"=>1, "interests"=>1, "cwlink"=> "https://codeworkout.cs.vt.edu/gym/workouts/955/practice")
Video.create("user"=>1, "video_id"=>"Z8m1l8_7uS4", "vtitle"=>"Boolean operators in C++ for Loggin In", "concepts"=>2, "interests"=>2, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1451/practice")
Video.create("user"=>1, "video_id"=>"aWmnyZ4lg6s", "vtitle"=>"Conditions in C++ to Dress for the Weather", "concepts"=>2, "interests"=>11, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1451/practice")
Video.create("user"=>1, "video_id"=>"NNOEIsJGaSU", "vtitle"=>"While loops in C++ for an Energy-Saving Thermostat", "concepts"=>3, "interests"=>12, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1469/practice")
Video.create("user"=>1, "video_id"=>"gmv6vYVZlZA", "vtitle"=>"For loops in C++ for Greetings", "concepts"=>4, "interests"=>10, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1510/practice")
Video.create("user"=>1, "video_id"=>"LlqCZMRbHxY", "vtitle"=>"For loops with Vectors in C++ for Workout Routines", "concepts"=>4, "interests"=>11, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1510/practice")
Video.create("user"=>1, "video_id"=>"sxPAo2A969E", "vtitle"=>"Switch statements in C++ for Horoscopes", "concepts"=>5, "interests"=>12, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1486/practice")
Video.create("user"=>1, "video_id"=>"6NqVry3dAoQ", "vtitle"=>"Vectors in C++ for a Task list", "concepts"=>6, "interests"=>16, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1058/practice")
Video.create("user"=>1, "video_id"=>"9rCRzRa66Is", "vtitle"=>"Vectors in C++ for a Workout Routine", "concepts"=>6, "interests"=>11, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1058/practice")
Video.create("user"=>1, "video_id"=>"au7BFUgcEKE", "vtitle"=>"Arrays in C++ for a Grocery List", "concepts"=>9, "interests"=>13, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1054/practice")
Video.create("user"=>1, "video_id"=>"i-JwayqWGR8", "vtitle"=>"Functions in C++ to Order Fast Food", "concepts"=>7, "interests"=>16, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1089/practice")
Video.create("user"=>1, "video_id"=>"AQTh0a2k9Hk", "vtitle"=>"Functions in C++ for Grocery Shopping", "concepts"=>7, "interests"=>13, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1089/practice")
Video.create("user"=>1, "video_id"=>"owLNe8Sj7kg", "vtitle"=>"Function Parameters in C++ for Editing Documents", "concepts"=>8, "interests"=>16, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1104/practice")
Video.create("user"=>1, "video_id"=>"hFmOhtavAbM", "vtitle"=>"Function Parameters in C++ for Borrowing Cars", "concepts"=>8, "interests"=>4, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1104/practice")
Video.create("user"=>1, "video_id"=>"be71kVpAPds", "vtitle"=>"Function Parameters in C++ for Updating Vectors", "concepts"=>8, "interests"=>1, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1104/practice")
Video.create("user"=>1, "video_id"=>"YGj-HgRFOk0", "vtitle"=>"Pointers Parameters in C++ for Recipes", "concepts"=>10, "interests"=>13, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1531/practice")
Video.create("user"=>1, "video_id"=>"uCoPsYcMWmU", "vtitle"=>"Structs in C++ for Apartments", "concepts"=>11, "interests"=>16, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1114/practice")
Video.create("user"=>1, "video_id"=>"KCFYYjVIjlk", "vtitle"=>"Structs in C++ for Superheroes", "concepts"=>11, "interests"=>8, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1114/practice")
Video.create("user"=>1, "video_id"=>"1x2MpDnY2Yw", "vtitle"=>"Classes in C++ for Video Streams", "concepts"=>12, "interests"=>2, "cwlink"=>"https://codeworkout.cs.vt.edu/gym/workouts/1116/practice")